name: Publish Integration images
on:
    push:
        branches:
            - develop
            - 'features/**'
            
jobs:
    push_to_registry:
        name: Push docker images to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Push API to Docker Hub
              uses: docker/build-push-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                file: ./Api/Dockerfile
                repository: lukasznowakowskiaxa/avanssur.axadeveloperdashboard.api
                tag_with_ref: true
                tags: lukasznowakowskiaxa/avanssur.axadeveloperdashboard.api:integration
            - name: Push UI to Docker Hub
              uses: docker/build-push-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                file: ./UI/Dockerfile
                repository: lukasznowakowskiaxa/avanssur.axadeveloperdashboard.ui
                tag_with_ref: true
                tags: lukasznowakowskiaxa/avanssur.axadeveloperdashboard.ui:integration